language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=config,pages,utility -m pytest

after_success:
  - coverage report --omit=.pytest_cache/*,bin/*,data/*,env/*,htmlcov/*,lib/*,scripts/*,tests/*
  - coveralls
